# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex Manly
email: alex.manly@contino.io
description: > # this means to ignore newlines until "baseurl:"
  I have been designing a writing enterpise application for 20 years. More
  recently I have specialised in automation, cloud and configuration management 
  and CI/CD.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: apmanly
github_username:  alexmanly
timezone: Europe/London
encoding: utf-8

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

#Any buzzword skills you want to include
skills:
 - Java
 - Groovy
 - Spring MVC
 - Spring Boot
 - REST
 - JPA
 - Ruby
 - Python
 - Bash
 - Powershell
 - Jenkins
 - AWS
 - Azure
 - Chef
 - Ansible
 - Puppet
 - Docker
 - Vagrant
 - Packer
 - Terraform
 - Vault
 - Consul

#Work experience is required
roles:
 - title: Principle DevOps Consultant
   start: 20166
   end: Ongoing
   employer: Contino
   description: Contino help Enterprise Organisations transform their software delivery engines. <br>We do this by delivering on key strategic technology initiatives whilst also upskilling our clients workforce and supporting the development of a more vibrant engineering culture.  Our key focus is on Cloud, Containers, Configuration Management, Automation and CI/CD.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 1997
   subject: Information Systema and Computer Science
   school: University of Leeds


#List of interesting Github repo/projects to include - optional
github:
 - alexmanly/hashicorp-demo
 - alexmanly/jenkins-docker
 - alexmanly/chef-oracle-db
 - alexmanly/chef-websphere

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/6253266/alex
   flairimageurl: http://stackoverflow.com/users/flair/6253266.png

