# Site settings
title: Alex Manly
twitter_username: apmanly
name: Alex Manly

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/alexmanly

#Any buzzword skills you want to include
skills:
 - Java
 - Groovy
 - Spring MVC
 - Spring Boot
 - REST
 - JPA
 - Ruby
 - Python
 - Bash
 - Powershell
 - Jenkins
 - AWS
 - Azure
 - Chef
 - Ansible
 - Puppet
 - Docker
 - Vagrant
 - Packer
 - Terraform
 - Vault
 - Consul

#Work experience is required
roles:
 - title: Principle DevOps Consultant
   start: 20166
   end: Ongoing
   employer: Contino
   description: Contino help Enterprise Organisations transform their software delivery engines. <br>We do this by delivering on key strategic technology initiatives whilst also upskilling our clients workforce and supporting the development of a more vibrant engineering culture.  Our key focus is on Cloud, Containers, Configuration Management, Automation and CI/CD.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 1997
   subject: Information Systema and Computer Science
   school: University of Leeds


#List of interesting Github repo/projects to include - optional
github:
 - alexmanly/hashicorp-demo
 - alexmanly/jenkins-docker
 - alexmanly/chef-oracle-db
 - alexmanly/chef-websphere

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/6253266/alex
   flairimageurl: http://stackoverflow.com/users/flair/6253266.png
